### ISSUE TITLE
It does not work!

### ISSUE THREAD

**Issue by RoderRUI** [zb980921/java-model-parser#1]
![image](https://github.com/zb81/java-model-parser/assets/49812273/c87e23cb-4821-4415-85f4-db57280a3f24)
## This program does not work with such java comments
![image](https://github.com/zb81/java-model-parser/assets/49812273/b913464a-9ae3-41d0-86b3-d110a275e74f)
## Please try to suit this code, I will appreciate it

**Comment by zb81** [comment]
Will update at weekend.
